name: Linter

on:
  push:
    branches:   # not sure if this is needed
      - '*'
  pull_request:
    types: [ opened, reopened ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3

  golangci-lint:
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up cache
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: days-since
          key: days-since-${{ hashFiles('go.mod') }}-${{ matrix.go-version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Must be specified without patch version: we always use the latest patch version.
          version: v1.42

          # If set to true then the action will use pre-installed Go
          skip-go-installation: true

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
