name: Release Drafter

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    steps:
      # Drafts release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5.12.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
